### ISSUE TITLE
EliasFanoMonotoneBigLongBigList is accidentally limited by LongArrayBitVector function

### ISSUE THREAD

**Issue by denatheinsti** [vigna/Sux4J#12]
Hi, love your libraries.  I am attempting to process a large graph that uses EliasFanoMonotoneBigLongBigList (mmapped, if it matters).  I've hit an issue where getLong is failing where lower bits = 9 and any long requested over 15.27 billion errors inside LongArrayBitVector.word().

It seems that the Big version of the EF list should be using the LongBigArrayBitVector version instead of the LongArrayBitVector, at least for the lowerbits.  Because the upperbits is still a single array limited to 2^31, there should probably be two functions.

**Comment by seirl** [comment]
This happens with the latest Software Heritage graph.

**Comment by vigna** [comment]
OK. 16 billions, will, indeed, exceed the capacity in the upper bits—frankly I didn't think about it. It is entirely true that we should use LongBigArrayBitVector—the problem is that we need a version of SimpleSelect that will work on that. I'll try to write one ASAP.

**Comment by vigna** [comment]
OK, that was too quick. The upper bit capacity is 128 billion bits, and I don't think the graph has 64 billion nodes. Can you provide a stack trace?

**Comment by vigna** [comment]
> It seems that the Big version of the EF list should be using the LongBigArrayBitVector version instead of the LongArrayBitVector, at least for the lowerbits. Because the upperbits is still a single array limited to 2^31, there should probably be two functions.

I really did skim through this, but it does not make any sense. The big version of EF uses a big array for lower bits. No limit.

**Comment by vigna** [comment]
This looks like an unforeseen integer overflow somewhere, but I need a replicable report. A stack trace is a start, but a piece of code would be ideal...

**Comment by denatheinsti** [comment]
This was the stack trace:

`Caused by: java.lang.AssertionError
        at it.unimi.dsi.bits.LongArrayBitVector.word(LongArrayBitVector.java:127)
        at it.unimi.dsi.sux4j.util.EliasFanoMonotoneBigLongBigList.getLong(EliasFanoMonotoneBigLongBigList.java:308)
        at it.unimi.dsi.big.webgraph.labelling.BitStreamArcLabelledImmutableGraph.offset(BitStreamArcLabelledImmutableGraph.java:182)
        at it.unimi.dsi.big.webgraph.labelling.BitStreamArcLabelledImmutableGraph$BitStreamLabelledArcIterator.<init>(BitStreamArcLabelledImmutableGraph.java:195)
        at it.unimi.dsi.big.webgraph.labelling.BitStreamArcLabelledImmutableGraph.successors(BitStreamArcLabelledImmutableGraph.java:239)
        at org.softwareheritage.graph.SwhUnidirectionalGraph.labelledSuccessors(SwhUnidirectionalGraph.java:209)
        at org.softwareheritage.graph.utils.ContentIdentifierWorker.checkSingleNode(ContentIdentifierWorker.java:142)`
        
And this is the function at line 127:

`	/**
	 * Returns the index of the word that holds a bit of specified index.
	 *
	 * @param index the index of a bit, or -1.
	 * @return the index of the word that holds the bit of given index, or -1 if {@code index} is -1.
	 */
	public static final int word(final long index) {
		assert index >>> LOG2_BITS_PER_WORD <= Integer.MAX_VALUE;
		return (int)(index >>> LOG2_BITS_PER_WORD);
	}`
    
Which is called from simply a labelledSuccessors iteration:

`    public ArcLabelledNodeIterator.LabelledArcIterator labelledSuccessors(long x) {
        if (labelledGraph == null) {
            throw new RuntimeException("Calling labelledNodeIterator() but labels were not loaded.");
        }
        return labelledGraph.successors(x);
    }`
    
Where x is > 15.28 billion and the graph was loaded with loadMapped().
    
More specifically, EF biglist is inside getLong:

`	public long getLong(final long index) {
		assert index >= 0;
		assert index < length;

		final int l = this.l;
		final long upperBits = selectUpper.select(index) - index;

		final long position = index * l;

		final int startWord = word(position);
		final int startBit = bit(position);
		final long result = BigArrays.get(lowerBits, startWord) >>> startBit;
		return upperBits << l | (startBit + l <= Long.SIZE ? result : result | BigArrays.get(lowerBits, startWord + 1) << -startBit) & lowerBitsMask;
	}`
	
And I'm pretty sure this.l is 9 and index is > 15.28 billion, so position is >137,520,000,000.  When shifted 64, 2,148,750,000 so greater than the maximum array allocation size.  Which, as you said, isn't a problem for a LongBigArrayBitVector, but the "word" function being called on line 308 is the NON big version of the function, so it asserts on line 127 of non-big LongArrayBitVector.

**Comment by vigna** [comment]
Ah, OK, now it's clear. It has nothing to do with LongArrayBigVector vs. LongBigArrayBitVector as a class. It's simply that the word() static method of LongArrayBigVector has an assert that checks that the resulting index is smaller than 2<sup>31</sup>. This is wrong, because in that position we are using a BigArray.get() and the index can be any long. So it's just a matter of using the right static method (indeed, the one in LongBigArrayBitVector instead of the one in LongArrayBigVector).

However, without realizing all this I implemented a version of EliasFanoMonotoneBigLongBigList that uses a big array for upper bits. This will increase the number of possible elements from approximately 64 billions to anything.

Do you guys think this has any sense? Clearly presently for Software Heritage this is not necessary, but I fell like having a "truly big" class would be useful. I'm measuring the slowdown and it seems really small.

**Comment by vigna** [comment]
BTW, the same problem appears in getDelta().

**Comment by seirl** [comment]
Thanks a lot for the investigation/fix! We shouldn't need arrays with >64 billion objects for at least several years, but if the slowdown is negligible, it does seems like it should be the way EFBigLongBigList is implemented.

**Comment by vigna** [comment]
I realized a left a LOT of int-things-that-should-be-long in that code. I did I thorough review but it's always very tricky.

**Comment by vigna** [comment]
I pushed a fixed version—let me know if it works for you. But I had to bump the serial version UID.

**Comment by seirl** [comment]
The new version seems to work, though it seems significantly slower than before.

Before:

    o.s.g.r.GraphServer - Elapsed: 15m 51s [25,340,003,876 deltas, 26,638,273.41 deltas/s, 37.54 ns/delta]

After:

    o.s.g.r.GraphServer - Elapsed: 40m 8s [25,340,003,876 deltas, 10,522,750.51 deltas/s, 95.03 ns/delta]

Though reading the log, it might just be a machine usage problem. I'll report later with better numbers.

**Comment by vigna** [comment]
That seems to be the case—the slowdown cannot be due to the class.

I have put together a slow unit test with 128B elements and 𝓁 = 3. This should somehow exercise all difficult parts of the code.

**Comment by seirl** [comment]
The load times seem to vary wildly, so it's definitely coming from our side. In any case, it seems that these were the last blockers for deploying the new graph. If you can make a new release of sux4j and webgraph-big, that would be perfect!

**Comment by vigna** [comment]
The large-scale test has shown a few other possible integer overflows. As soon as it passes, I'll send out everything!
